name: Submission Check "Drawing with LLMs"

on:
  schedule:
    - cron: "*/5 * * * *"  # 5分おきに実行
  workflow_dispatch:        # 手動実行可

jobs:
  check-submission:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install kaggle requests python-dotenv

      - name: Set up Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          # ファイルが正しく作成されたか確認
          ls -la ~/.kaggle/kaggle.json

      - name: Run python script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          python Submit/submit_notification.py